name: fitness_app
description: Fitness App with Mono Setup.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.10.4'
dev_dependencies:
  melos: ^3.1.1
  very_good_analysis: ^5.0.0+1


  