name: fitness_components
description: Fitness App with Mono Setup.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.10.4'

dependencies: 
  fitness_resources: any 
  flutter:  
    sdk: flutter
  flutter_screenutil: ^5.8.4  
  flutter_svg: ^2.0.7   
  vector_graphics: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
  
flutter:
  generate: true
  uses-material-design: true
  