name: Fitness_App_Components
description: Fitness App with Mono Setup.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.10.4'

dependencies: 
  flutter:  
    sdk: flutter
  flutter_svg: ^2.0.7   
  Fitness_App_Resources: any
  vector_graphics: ^1.1.7


flutter:
  generate: true
  uses-material-design: true
  