name: fitness
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fitness_components: any
  fitness_resources: any
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  syncfusion_flutter_charts: ^22.2.8


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  generate: true




