name: Fitness_App_Resources
description: Fitness App with Mono Setup.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.10.4'
dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_graphics_compiler: ^1.1.7
  
flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons-bin/
    - assets/images-bin/