// File generated by "melos run svg". Do not edit by hand.
// Copyright (c) 2023. The Hridayangam Authors. All rights reserved.

class Asset {
  static const AssetImages images = AssetImages();
}

class AssetImages {
  const AssetImages();

  String get men => 'assets/images-bin/men.svg.vec';
}
